// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Ozon Shrtner WebSite Backend Service",
    "title": "Ozon Shrtner Backend Service",
    "version": "development"
  },
  "paths": {
    "/original_link": {
      "get": {
        "tags": [
          "Link"
        ],
        "summary": "Get Original Link",
        "operationId": "GetOriginalLink",
        "parameters": [
          {
            "type": "string",
            "description": "Short Link",
            "name": "ShortLink",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Original Link Response",
            "schema": {
              "$ref": "#/definitions/OriginalLink"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/shortner_link": {
      "post": {
        "tags": [
          "Link"
        ],
        "summary": "Create Short Link",
        "operationId": "CreateShortLink",
        "parameters": [
          {
            "description": "Create Short Link",
            "name": "OriginalLink",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OriginalLink"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create Short Link Response",
            "schema": {
              "$ref": "#/definitions/ShortLink"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "OriginalLink": {
      "type": "object",
      "required": [
        "original_link"
      ],
      "properties": {
        "original_link": {
          "type": "string"
        }
      }
    },
    "ShortLink": {
      "type": "object",
      "required": [
        "short_link"
      ],
      "properties": {
        "short_link": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Ozon Shrtner WebSite Backend Service",
    "title": "Ozon Shrtner Backend Service",
    "version": "development"
  },
  "paths": {
    "/original_link": {
      "get": {
        "tags": [
          "Link"
        ],
        "summary": "Get Original Link",
        "operationId": "GetOriginalLink",
        "parameters": [
          {
            "type": "string",
            "description": "Short Link",
            "name": "ShortLink",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Original Link Response",
            "schema": {
              "$ref": "#/definitions/OriginalLink"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/shortner_link": {
      "post": {
        "tags": [
          "Link"
        ],
        "summary": "Create Short Link",
        "operationId": "CreateShortLink",
        "parameters": [
          {
            "description": "Create Short Link",
            "name": "OriginalLink",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OriginalLink"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Create Short Link Response",
            "schema": {
              "$ref": "#/definitions/ShortLink"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "OriginalLink": {
      "type": "object",
      "required": [
        "original_link"
      ],
      "properties": {
        "original_link": {
          "type": "string"
        }
      }
    },
    "ShortLink": {
      "type": "object",
      "required": [
        "short_link"
      ],
      "properties": {
        "short_link": {
          "type": "string"
        }
      }
    }
  }
}`))
}
