// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/ozon_shortner/internal/api/definition"
)

// NewCreateShortLinkParams creates a new CreateShortLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateShortLinkParams() *CreateShortLinkParams {
	return &CreateShortLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateShortLinkParamsWithTimeout creates a new CreateShortLinkParams object
// with the ability to set a timeout on a request.
func NewCreateShortLinkParamsWithTimeout(timeout time.Duration) *CreateShortLinkParams {
	return &CreateShortLinkParams{
		timeout: timeout,
	}
}

// NewCreateShortLinkParamsWithContext creates a new CreateShortLinkParams object
// with the ability to set a context for a request.
func NewCreateShortLinkParamsWithContext(ctx context.Context) *CreateShortLinkParams {
	return &CreateShortLinkParams{
		Context: ctx,
	}
}

// NewCreateShortLinkParamsWithHTTPClient creates a new CreateShortLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateShortLinkParamsWithHTTPClient(client *http.Client) *CreateShortLinkParams {
	return &CreateShortLinkParams{
		HTTPClient: client,
	}
}

/*
CreateShortLinkParams contains all the parameters to send to the API endpoint

	for the create short link operation.

	Typically these are written to a http.Request.
*/
type CreateShortLinkParams struct {

	/* OriginalLink.

	   Create Short Link
	*/
	OriginalLink *models.OriginalLink

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create short link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateShortLinkParams) WithDefaults() *CreateShortLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create short link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateShortLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create short link params
func (o *CreateShortLinkParams) WithTimeout(timeout time.Duration) *CreateShortLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create short link params
func (o *CreateShortLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create short link params
func (o *CreateShortLinkParams) WithContext(ctx context.Context) *CreateShortLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create short link params
func (o *CreateShortLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create short link params
func (o *CreateShortLinkParams) WithHTTPClient(client *http.Client) *CreateShortLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create short link params
func (o *CreateShortLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOriginalLink adds the originalLink to the create short link params
func (o *CreateShortLinkParams) WithOriginalLink(originalLink *models.OriginalLink) *CreateShortLinkParams {
	o.SetOriginalLink(originalLink)
	return o
}

// SetOriginalLink adds the originalLink to the create short link params
func (o *CreateShortLinkParams) SetOriginalLink(originalLink *models.OriginalLink) {
	o.OriginalLink = originalLink
}

// WriteToRequest writes these params to a swagger request
func (o *CreateShortLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OriginalLink != nil {
		if err := r.SetBodyParam(o.OriginalLink); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
