// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOriginalLinkParams creates a new GetOriginalLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOriginalLinkParams() *GetOriginalLinkParams {
	return &GetOriginalLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOriginalLinkParamsWithTimeout creates a new GetOriginalLinkParams object
// with the ability to set a timeout on a request.
func NewGetOriginalLinkParamsWithTimeout(timeout time.Duration) *GetOriginalLinkParams {
	return &GetOriginalLinkParams{
		timeout: timeout,
	}
}

// NewGetOriginalLinkParamsWithContext creates a new GetOriginalLinkParams object
// with the ability to set a context for a request.
func NewGetOriginalLinkParamsWithContext(ctx context.Context) *GetOriginalLinkParams {
	return &GetOriginalLinkParams{
		Context: ctx,
	}
}

// NewGetOriginalLinkParamsWithHTTPClient creates a new GetOriginalLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOriginalLinkParamsWithHTTPClient(client *http.Client) *GetOriginalLinkParams {
	return &GetOriginalLinkParams{
		HTTPClient: client,
	}
}

/*
GetOriginalLinkParams contains all the parameters to send to the API endpoint

	for the get original link operation.

	Typically these are written to a http.Request.
*/
type GetOriginalLinkParams struct {

	/* ShortLink.

	   Short Link
	*/
	ShortLink string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get original link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOriginalLinkParams) WithDefaults() *GetOriginalLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get original link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOriginalLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get original link params
func (o *GetOriginalLinkParams) WithTimeout(timeout time.Duration) *GetOriginalLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get original link params
func (o *GetOriginalLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get original link params
func (o *GetOriginalLinkParams) WithContext(ctx context.Context) *GetOriginalLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get original link params
func (o *GetOriginalLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get original link params
func (o *GetOriginalLinkParams) WithHTTPClient(client *http.Client) *GetOriginalLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get original link params
func (o *GetOriginalLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithShortLink adds the shortLink to the get original link params
func (o *GetOriginalLinkParams) WithShortLink(shortLink string) *GetOriginalLinkParams {
	o.SetShortLink(shortLink)
	return o
}

// SetShortLink adds the shortLink to the get original link params
func (o *GetOriginalLinkParams) SetShortLink(shortLink string) {
	o.ShortLink = shortLink
}

// WriteToRequest writes these params to a swagger request
func (o *GetOriginalLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param ShortLink
	qrShortLink := o.ShortLink
	qShortLink := qrShortLink
	if qShortLink != "" {

		if err := r.SetQueryParam("ShortLink", qShortLink); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
