// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/ozon_shortner/internal/api/definition"
)

// GetOriginalLinkReader is a Reader for the GetOriginalLink structure.
type GetOriginalLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOriginalLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOriginalLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOriginalLinkBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetOriginalLinkInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /original_link] GetOriginalLink", response, response.Code())
	}
}

// NewGetOriginalLinkOK creates a GetOriginalLinkOK with default headers values
func NewGetOriginalLinkOK() *GetOriginalLinkOK {
	return &GetOriginalLinkOK{}
}

/*
GetOriginalLinkOK describes a response with status code 200, with default header values.

Original Link Response
*/
type GetOriginalLinkOK struct {
	Payload *models.OriginalLink
}

// IsSuccess returns true when this get original link o k response has a 2xx status code
func (o *GetOriginalLinkOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get original link o k response has a 3xx status code
func (o *GetOriginalLinkOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get original link o k response has a 4xx status code
func (o *GetOriginalLinkOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get original link o k response has a 5xx status code
func (o *GetOriginalLinkOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get original link o k response a status code equal to that given
func (o *GetOriginalLinkOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get original link o k response
func (o *GetOriginalLinkOK) Code() int {
	return 200
}

func (o *GetOriginalLinkOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /original_link][%d] getOriginalLinkOK %s", 200, payload)
}

func (o *GetOriginalLinkOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /original_link][%d] getOriginalLinkOK %s", 200, payload)
}

func (o *GetOriginalLinkOK) GetPayload() *models.OriginalLink {
	return o.Payload
}

func (o *GetOriginalLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OriginalLink)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOriginalLinkBadRequest creates a GetOriginalLinkBadRequest with default headers values
func NewGetOriginalLinkBadRequest() *GetOriginalLinkBadRequest {
	return &GetOriginalLinkBadRequest{}
}

/*
GetOriginalLinkBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetOriginalLinkBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get original link bad request response has a 2xx status code
func (o *GetOriginalLinkBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get original link bad request response has a 3xx status code
func (o *GetOriginalLinkBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get original link bad request response has a 4xx status code
func (o *GetOriginalLinkBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get original link bad request response has a 5xx status code
func (o *GetOriginalLinkBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get original link bad request response a status code equal to that given
func (o *GetOriginalLinkBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get original link bad request response
func (o *GetOriginalLinkBadRequest) Code() int {
	return 400
}

func (o *GetOriginalLinkBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /original_link][%d] getOriginalLinkBadRequest %s", 400, payload)
}

func (o *GetOriginalLinkBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /original_link][%d] getOriginalLinkBadRequest %s", 400, payload)
}

func (o *GetOriginalLinkBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOriginalLinkBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOriginalLinkInternalServerError creates a GetOriginalLinkInternalServerError with default headers values
func NewGetOriginalLinkInternalServerError() *GetOriginalLinkInternalServerError {
	return &GetOriginalLinkInternalServerError{}
}

/*
GetOriginalLinkInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetOriginalLinkInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get original link internal server error response has a 2xx status code
func (o *GetOriginalLinkInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get original link internal server error response has a 3xx status code
func (o *GetOriginalLinkInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get original link internal server error response has a 4xx status code
func (o *GetOriginalLinkInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get original link internal server error response has a 5xx status code
func (o *GetOriginalLinkInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get original link internal server error response a status code equal to that given
func (o *GetOriginalLinkInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get original link internal server error response
func (o *GetOriginalLinkInternalServerError) Code() int {
	return 500
}

func (o *GetOriginalLinkInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /original_link][%d] getOriginalLinkInternalServerError %s", 500, payload)
}

func (o *GetOriginalLinkInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /original_link][%d] getOriginalLinkInternalServerError %s", 500, payload)
}

func (o *GetOriginalLinkInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOriginalLinkInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
