// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetOriginalLinkParams creates a new GetOriginalLinkParams object
//
// There are no default values defined in the spec.
func NewGetOriginalLinkParams() GetOriginalLinkParams {

	return GetOriginalLinkParams{}
}

// GetOriginalLinkParams contains all the bound params for the get original link operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetOriginalLink
type GetOriginalLinkParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Short Link
	  Required: true
	  In: query
	*/
	ShortLink string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOriginalLinkParams() beforehand.
func (o *GetOriginalLinkParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qShortLink, qhkShortLink, _ := qs.GetOK("ShortLink")
	if err := o.bindShortLink(qShortLink, qhkShortLink, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindShortLink binds and validates parameter ShortLink from query.
func (o *GetOriginalLinkParams) bindShortLink(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("ShortLink", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("ShortLink", "query", raw); err != nil {
		return err
	}
	o.ShortLink = raw

	return nil
}
