// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OriginalLink original link
//
// swagger:model OriginalLink
type OriginalLink struct {

	// original link
	// Required: true
	OriginalLink *string `json:"original_link"`
}

// Validate validates this original link
func (m *OriginalLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOriginalLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OriginalLink) validateOriginalLink(formats strfmt.Registry) error {

	if err := validate.Required("original_link", "body", m.OriginalLink); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this original link based on context it is used
func (m *OriginalLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OriginalLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OriginalLink) UnmarshalBinary(b []byte) error {
	var res OriginalLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
