// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ShortLink short link
//
// swagger:model ShortLink
type ShortLink struct {

	// short link
	// Required: true
	ShortLink *string `json:"short_link"`
}

// Validate validates this short link
func (m *ShortLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateShortLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ShortLink) validateShortLink(formats strfmt.Registry) error {

	if err := validate.Required("short_link", "body", m.ShortLink); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this short link based on context it is used
func (m *ShortLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ShortLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShortLink) UnmarshalBinary(b []byte) error {
	var res ShortLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
